costmap:
  costmap:
    ros__parameters:
      global_frame: odom
      update_frequency: 10.0
      publish_frequency: 5.0
      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05
      robot_base_frame: base_link
      plugins: ["stvl_layer", "inflation_layer"]
      stvl_layer:
        plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
        enabled: true
        voxel_decay: 15.0
        decay_model: 0
        voxel_size: 0.05
        track_unknown_space: true
        mark_threshold: 0
        observation_sources: depth_points
        depth_points:
          topic: /camera/camera/depth/color/points
          data_type: PointCloud2
          sensor_frame: camera_depth_optical_frame
          marking: true
          clearing: true
          obstacle_range: 3.0
          min_obstacle_height: 0.05
          max_obstacle_height: 2.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
        cost_scaling_factor: 3.0
