// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1774017725);
user_pref("app.update.lastUpdateTime.region-update-timer", 1774017725);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1774017725);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1774017725);
user_pref("browser.region.update.updated", 1774017701);
user_pref("browser.search.region", "NL");
user_pref("calendar.caldav.googleResync", 1774017699);
user_pref("calendar.list.sortOrder", "e4454256-9432-4e11-8f09-c5383b1b4045");
user_pref("calendar.registry.e4454256-9432-4e11-8f09-c5383b1b4045.calendar-main-default", true);
user_pref("calendar.registry.e4454256-9432-4e11-8f09-c5383b1b4045.calendar-main-in-composite", true);
user_pref("calendar.registry.e4454256-9432-4e11-8f09-c5383b1b4045.disabled", true);
user_pref("calendar.registry.e4454256-9432-4e11-8f09-c5383b1b4045.name", "Home");
user_pref("calendar.registry.e4454256-9432-4e11-8f09-c5383b1b4045.type", "storage");
user_pref("calendar.registry.e4454256-9432-4e11-8f09-c5383b1b4045.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Amsterdam");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "b82d739c-902d-4d7c-b056-254da876f2f4");
user_pref("datareporting.dau.cachedUsageProfileID", "82c78c0d-6a69-4079-85de-84df6b8a7e91");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1774017708572");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.cache.lastUpdate", 1774017728);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.hasExperimentsInstalled", false);
user_pref("extensions.hasExtensionsInstalled", false);
user_pref("extensions.lastAppBuildId", "20260123195141");
user_pref("extensions.lastAppVersion", "140.7.1");
user_pref("extensions.lastPlatformVersion", "140.7.0");
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"1975a309-eebc-4026-9976-27dc6435111f\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ui-rdf.version", 51);
user_pref("mailnews.database.global.datastore.id", "fbcdf2fb-af9b-4d12-af7a-463cf12937a");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.start_page.url", "https://duck.com");
user_pref("mailnews.start_page_override.mstone", "140.7.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("services.settings.clock_skew_seconds", -21163);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1774038890);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1774038890);
user_pref("services.settings.thunderbird.search-config.last_check", 1774038890);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1774038890);
user_pref("toolkit.startup.last_success", 1774017780);
user_pref("toolkit.telemetry.cachedClientID", "a3a96f0c-4dee-4bda-9c7a-b715e39de7bd");
user_pref("toolkit.telemetry.cachedProfileGroupID", "34e58ef3-b1f9-4fde-b310-5fdd4f5f2b2b");
user_pref("toolkit.telemetry.previousBuildID", "20260123195141");
