imu_filter_madgwick:
  ros__parameters:
    use_mag: false # we don't have a magnetometer
    publish_tf: false # do not publish a map->odom frame that only contains rotation

depthimage_to_laserscan:
    ros__parameters:
      # limit the range to cut out the primordial soup
      # (the depth camera is wildly inaccurate past 2 meters)
      range_min: 0.1
      range_max: 2.0
