global_costmap:
  global_costmap:
    ros__parameters:
      publish_frequency: 2.
      update_frequency: 5.
      plugins:
        - static_layer
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true

local_costmap:
  local_costmap:
    ros__parameters:
      publish_frequency: 2.
      update_frequency: 5.
      rolling_window: true
      plugins:
        - stvl_layer
      stvl_layer:
        plugin: 'nav2_costmap_2d::VoxelLayer'
        publish_voxel_map: true
        origin_z: -1.
        z_resolution: 0.2 # height of one voxel, in meters
        z_voxels: 16 # height of the map, in voxels
        observation_sources: depth_cam
        depth_cam:
          data_type: PointCloud2
          topic: /camera/camera/depth/color/points
          expected_update_rate: 1. # scream if the topic goes silent
          marking: true
          clearing: true
          max_obstacle_height: 3.

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      critics: ['GoalDist'] # sybau bro, here's your critic
