/rtabmap:
  rgbd_odometry:
    ros__parameters:
      # assume that the rover is stationary,
      # use the first IMU sample to set initial pose
      wait_imu_to_init: true

  rtabmap:
    ros__parameters: {}
      # subscribe_depth: true
      # subscribe_odom_info: true
